name: Manual Deploy

on: 
  workflow_dispatch:  
    inputs:
      environment:
        description: 'Select environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy App
        run: echo "Deploying to ${{ github.event.inputs.environment }} environment."
