name: Incident Handler

on:
  repository_dispatch:
    types: [incident-report]

jobs:
  handle-incident:
    runs-on: ubuntu-latest

    steps:
      - name: Print incident report
        run: echo " Incident reported"
